apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "250M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "90"
    nais.io/read-only-file-system: "false"
    nais.io/run-as-user: "1001"
  name: soknad-api
  namespace: aap
  labels:
    team: aap
spec:
  observability:
    tracing:
      enabled: true
  leaderElection: true
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
        role: roles/cloudkms.admin
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
        role: roles/cloudkms.cryptoKeyEncrypterDecrypter
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
        role: roles/cloudsql.client
    sqlInstances:
      - name: aap-soknad-api-{{env}}
        type: POSTGRES_14
        tier: db-custom-1-3840
        diskAutoresize: true
        diskType: SSD
        databases:
          - name: aap-soknad-api-{{env}}
            envVarPrefix: DB
    buckets:
      - name: aap-vedlegg-{{env}}
        cascadingDelete: true
        lifecycleCondition:
          numNewerVersions: 0
          age: {{vedlegg-varighet}}
      - name: aap-mellomlagring-{{env}}
        cascadingDelete: true
        lifecycleCondition:
          numNewerVersions: 0
          age: {{mellomlagring-varighet}}
  accessPolicy:
    inbound:
      rules:
        - application: innsending
        - application: ettersporre-dokumentasjon
        - application: soknad
        - application: innsyn
        - application: tms-min-side-proxy
          namespace: min-side    
    outbound:
      external:
        - host: dokarkiv.{{env}}-fss-pub.nais.io
        - host: {{saf}}
        - host: pdl-api.{{env}}-fss-pub.nais.io
      rules:
        - application: tempo-distributor
          namespace: nais-system
        - application: sokos-kontoregister-person
          namespace: okonomi
        - application: clamav
          namespace: nais-system
        - application: pdfgen
        - application: digdir-krr-proxy
          namespace: team-rocket
        - application: isdialogmelding
          namespace: teamsykefravr
  tokenx:
    enabled: true
  kafka:
    pool: nav-{{env}}
  port: 8080
  image: {{image}}
  liveness:
    path: /actuator/health/liveness
    initialDelay: 60
  readiness:
    path: /actuator/health/readiness
    initialDelay: 60
  prometheus:
    enabled: true
    path: /actuator/prometheus
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  ingresses:
    - {{ingress}}
  resources:
    limits:
      memory: 8192Mi
    requests:
      cpu: 250m
      memory: 4096Mi
  env:
    - name: MELLOMLAGRING_VARIGHET
      value: "{{mellomlagring-varighet}}"
    - name: MELLOMLAGRING_NAVN
      value: aap-mellomlagring-{{env}}
    - name: VEDLEGG_VARIGHET
      value: "{{vedlegg-varighet}}"
    - name: VEDLEGG_NAVN
      value: aap-vedlegg-{{env}}
    - name: ENV
      value: {{env}}