management:
    endpoints:
        web:
            exposure:
                include: '*'
    endpoint:
        health:
            show-details: always
no.nav:
    security:
        jwt:
            client:
                registration:
                    aareg-services-q1:
                        token-exchange:
                            audience: ${onprem}:arbeidsforhold:aareg-services-nais-q1
spring:
    mvc:
        log-request-details: true
server:
    error:
        whitelabel:
            enabled: false
arbeidsforhold:
    base-uri: https://aareg-services-q1.dev-fss-pub.nais.io
organisasjon:
    base-uri: https://ereg-services-q1.dev-fss-pub.nais.io

logging:
    level:
        org:
            springframework:
                transaction:
                    interceptor: trace