management :
  endpoints:
    web:
      exposure:
        include:  '*'
  endpoint:
    health:
      show-details : always
no.nav:
  security:
    jwt:
      issuer:
        idporten:
          proxy-url: http://webproxy.nais:8088
  mvc:
    log-request-details : true