management:
    endpoints:
        web:
            exposure:
                include: '*'
    endpoint:
        health:
            show-details: always
no.nav:
    security:
        jwt:
            client:
                registration:
                    aareg-services-q1:
                        token-exchange:
                            audience: ${onprem}:arbeidsforhold:aareg-services-nais-q1
spring:
    mvc:
        log-request-details: true
server:
    error:
        whitelabel:
            enabled: false
arbeidsforhold:
    base-uri: https://aareg-services-q1.dev-fss-pub.nais.io
    enabled: false
organisasjon:
    base-uri: https://ereg-services-q1.dev-fss-pub.nais.io
    enabled: false
buckets:
    id: ${gcp.team.project.id}
    kms:
        ring: aap-mellomlagring-kms
        key: ${buckets.kms.ring}-key
    mellom:
        navn: ${mellomlagring.navn}
        subscription: ${buckets.mellom.navn}-subscription
        topic: ${buckets.mellom.navn}-topic
        kms: projects/${buckets.id}/locations/europe-north1/keyRings/aap-mellomlagring-kms/cryptoKeys/mellomlagring
    vedlegg:
        navn: ${vedlegg.navn}
        subscription: ${buckets.vedlegg.navn}-subscription
        topic: ${buckets.vedlegg.navn}-topic
        kms: ${buckets.mellom.kms}
        typer:
            - application/pdf
            - image/jpeg
            - image/png



debug: false