management :
  endpoints:
    web:
      exposure:
        include:  '*'
  endpoint:
      health:
        show-details : always
no.nav:
  security:
    jwt:
      client:
        registration:
          pdl-api:
            token-exchange:
              audience: dev-fss:pdl:pdl-api
spring:
 mvc:
   log-request-details : true
pdl:
  base-uri: https://pdl-api.dev-fss-pub.nais.io/graphql
sts:
  base-uri: https://security-token-service.dev.adeo.no