
info:
  cluster-name: ${nais.cluster.name}
  image-name : ${nais.image.name}
  java-vendor : ${java.version}
  namespace-name: ${nais.namespace.name}
spring:
  main:
    banner-mode: off
  jackson:
    default-property-inclusion: non_empty
    mapper:
      accept-case-insensitive-enums: true
      accept-case-insensitive-properties: true
    deserialization:
      read-unknown-enum-values-using-default-value: true
      accept-single-value-as-array: true
      fail-on-unknown-properties: true
    serialization:
      write-empty-json-arrays: false
      fail-on-empty-beans: false
management :
  endpoints:
    web:
      exposure:
        include:  '*'
  endpoint:
    health:
      ping:
        enabled: false
      diskspace:
          enabled: false
      show-details : always
no.nav:
  security:
    jwt:
      client:
        registration:
          pdl-api:
            token-exchange:
              audience: dev-fss:pdl:pdl-api
            well-known-url: ${token.x.well.known.url}
            grant-type: urn:ietf:params:oauth:grant-type:token-exchange
            authentication:
              client-id: ${token.x.client.id}
              client-jwk: ${token.x.private.jwk}
              client-auth-method: private_key_jwt
      issuer:
        tokenx:
          discovery-url: ${token.x.well.known.url}
          accepted-audience: ${token.x.client.id}
        idporten:
          validation:
             optional_claims: aud,nbf
          accepted_audience: ${idporten.client.id}
          discovery-url:  ${idporten.well.known.url}
mvc:
  log-request-details : true
pdl:
  base-uri: https://pdl-api.dev-fss-pub.nais.io/graphql