management:
    endpoints:
        web:
            exposure:
                include: '*'
    endpoint:
        health:
            show-details: always
no.nav:
    security:
        jwt:
            client:
                registration:
                    digdir-krr-proxy:
                        token-exchange:
                            audience: dev-gcp:team-rocket:digdir-krr-proxy
                    aap-fss-proxy:
                        token-exchange:
                            audience: dev-fss:aap:fss-proxy
                    aareg-services-q1:
                        token-exchange:
                            audience: dev-fss:arbeidsforhold:aareg-services-nais-q1
                    isdialogmelding:
                        token-exchange:
                            audience: dev-gcp:teamsykefravr:isdialogmelding
                    pdl-api:
                        token-exchange:
                            audience: dev-fss:pdl:pdl-api
spring:
    mvc:
        log-request-details: true
behandler:
    base-uri: https://isdialogmelding.dev.intern.nav.no
organisasjon:
    base-uri: https://aap-fss-proxy.dev-fss-pub.nais.io
pdl:
    base-uri: https://pdl-api.dev-fss-pub.nais.io/graphql
    scope: api://dev-fss.pdl.pdl-api/.default