management:
    endpoints:
        web:
            exposure:
                include: '*'
    endpoint:
        health:
            show-details: always
no.nav:
    security:
        jwt:
            client:
                registration:
                    aareg-services-q1:
                        token-exchange:
                            audience: ${onprem}:arbeidsforhold:aareg-services-nais-q1
spring:
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    mvc:
        log-request-details: true
server:
    error:
        whitelabel:
            enabled: false
arbeidsforhold:
    base-uri: https://aareg-services-q1.dev-fss-pub.nais.io
    enabled: false
organisasjon:
    base-uri: https://ereg-services-q1.dev-fss-pub.nais.io
    enabled: false
saf:
    base-uri: https://safselvbetjening-q1.${onprem}-pub.nais.io/graphql
konto:
    enabled: true
joark:
    scope: api://${onprem}.teamdokumenthandtering.dokarkiv-q1/.default
minside:
    backlinks:
        innsyn: https://aap-innsyn.dev.nav.no/aap/innsyn
        standard: https://aap-soknad.dev.nav.no/aap/soknad/standard
        utland: https://aap-soknad.dev.nav.no/aap/soknad/utland