management:
    endpoints:
        web:
            exposure:
                include: '*'
    endpoint:
        health:
            show-details: always
no.nav:
    security:
        jwt:
            client:
                registration:
                    aareg-services:
                        token-exchange:
                            audience: prod-fss:arbeidsforhold:aareg-services-nais
                        well-known-url: ${token.x.well.known.url}
                        grant-type: urn:ietf:params:oauth:grant-type:token-exchange
                        authentication:
                            client-id: ${token.x.client.id}
                            client-jwk: ${token.x.private.jwk}
                            client-auth-method: private_key_jwt

                    safselvbetjening:
                        token-exchange:
                            audience: prod-fss:teamdokumenthandtering:safselvbetjening
                        well-known-url: ${token.x.well.known.url}
                        grant-type: urn:ietf:params:oauth:grant-type:token-exchange
                        authentication:
                            client-id: ${token.x.client.id}
                            client-jwk: ${token.x.private.jwk}
                            client-auth-method: private_key_jwt

arbeidsforhold:
    base-uri: https://aareg-services.prod-fss-pub.nais.io
organisasjon:
    base-uri: https://ereg-services.prod-fss-fss-pub.nais.io
saf:
    base-uri: https://safselvbetjening.prod-fss-pub.nais.io
konto:
    enabled: false
vl:
    enabled: false
    standard:
        enabled: false
    ettersending:
        enabled: false
    utland:
        enabled: false
joark:
    scope: api://prod-fss.teamdokumenthandtering.dokarkiv/.default
minside:
    backlinks:
        innsyn: https://www.nav.no/aap/mine-aap
        standard: https://www.nav.no/aap/soknad
        utland: https://aap-soknad.nav.no/aap/soknad/utland