management :
  endpoints:
    web:
      exposure:
        include:  '*'
  endpoint:
      health:
        show-details : always
no.nav:
  security:
    jwt:
      client:
        registration:
          client-credentials-pdl:
            token-endpoint-url: ${azure.openid.config.token.endpoint}
            grant-type: client_credentials
            scope: ${pdl.scope}
            authentication:
              client-id: ${azure.app.client.id}
              client-jwk: ${azure.app.jwk}
              client-auth-method: private_key_jwt
          isdialogmelding:
            token-exchange:
              audience: dev-gcp:teamsykefravr:isdialogmelding
          pdl-api:
            token-exchange:
              audience: dev-fss:pdl:pdl-api
spring:
 mvc:
   log-request-details : true
fastlege:
  base-uri: https://isdialogmelding.dev.intern.nav.no
pdl:
  base-uri: https://pdl-api.dev-fss-pub.nais.io/graphql
  scope:    api://dev-fss.pdl.pdl-api/.default