management :
  endpoints:
    web:
      exposure:
        include:  '*'
  endpoint:
    health:
      show-details : always
no.nav:
  security:
    jwt:
      issuer:
        idporten:
          validation:
            optional_claims: aud,nbf
          accepted_audience: ${idporten.client.id}
          discovery-url:  ${idporten.well.known.url}
  mvc:
    log-request-details : true