apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: aap-hello-world
  namespace: aap
  labels:
    team: aap
spec:
  image: {{image}}
  port: 8080
  replicas:
      min: 2
      max: 2
      cpuThresholdPercentage: 50
  liveness:
      path: /internal/actuator/health/liveness
      initialDelay: 60
  readiness:
      path: /internal/actuator/health/readiness
      initialDelay: 60
  prometheus:
      enabled: true
      path: /internal/actuator/prometheus
  replicas:
      min: 2
      max: 2
      cpuThresholdPercentage: 50
  ingresses:
{{#each ingresses as |url|}}
    - {{url}}
{{/each}}
  resources:
      limits:
         cpu: 1500m
         memory: 3072Mi
      requests:
         cpu: 250m
         memory: 1536Mi
{{#unless gcp}}
  webproxy: true
{{/unless}}
