name: Bygg og deploy

on:
    push:
        branches:
            - main
        paths-ignore:
            - '**.md'
env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    IMAGE_BASE: ghcr.io/${{ github.repository }}
    APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}

jobs:
    bygg:
        runs-on: ubuntu-latest
        outputs:
            image: ${{ steps.step1.outputs.image }}
        steps:
            -   name: Sjekker ut kode
                uses: actions/checkout@v3

            -   name: Setter opp Java 17
                uses: actions/setup-java@v3
                with:
                    java-version: 17
                    distribution: temurin
                    cache: maven

            -   name: Installerer cosign
                uses: sigstore/cosign-installer@main
                with:
                    cosign-release: 'v1.3.1'

            -   name: Verifiserer distroless base-image
                run:  cosign verify --key distroless.pub gcr.io/distroless/java17

            -   name: Setter tag-navn
                run: echo "TAG=$(date +%Y.%m.%d.%H%M%S)-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

            -   name: Setter image-navn
                id: step1
                run: |
                   echo "IMAGE=$(echo $IMAGE_BASE):$(echo $TAG)" >> $GITHUB_ENV
                   echo "::set-output name=image::$(echo $IMAGE)"

            -   name: Kompilerer og bygger image
                run: ./mvnw --settings .github/.m2/settings.xml -Drevision=${TAG} package jib:build

            -   name: Deployer til dev
                uses: nais/deploy/actions/deploy@master
                env:
                    PRINT_PAYLOAD: true
                    APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                    CLUSTER: dev-gcp
                    RESOURCE: .nais/naiserator.yaml,.nais/alerts.yaml
                    VARS: .nais/dev.json

    var-test:
        env:
          IMG: ${{needs.bygg.outputs.image}}
        name: var passing test
        runs-on: ubuntu-latest
        needs: bygg
        steps:
            - run:  echo "IMAGE=$(echo $IMG)" >> $GITHUB_ENV
            - name: Next
              run: echo $IMAGE