name: Build PR or branch

on:
    pull_request:
        branches:
            - main
        paths-ignore:
            - '**.md'
env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    kompiler:
        runs-on: ubuntu-latest
        outputs:
            image: ${{ steps.kompiler-pr.outputs.image }}
        steps:
            -  name: Print Title of PR
               run: echo The Title of your PR is ${{ github.event.pull_request.title }}

            -   name: Sjekk ut kode
                uses: actions/checkout@v3

            -   name: Sett opp Java 17
                uses: actions/setup-java@v3
                with:
                    java-version: 17
                    distribution: temurin
                    cache: maven

            -   name: Setter tag-navn
                run: echo "TAG=$(date +%Y.%m.%d.%H%M%S)-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

            -   name: Setter image-navn
                run: echo "IMAGE=$(echo $IMAGE_BASE):$(echo $TAG)" >> $GITHUB_ENV

            -   name: Kompiler
                id: kompiler-pr
                run: |
                    echo "image=${{ env.IMAGE }}" >> $GITHUB_OUTPUT
                    ./mvnw test --batch-mode --quiet --settings .github/.m2/settings.xml