name: Deploy kafka topics

on:
  push:
    branches:
      - main
    paths:
      - kafka-aiven/**
      - '!kafka-aiven/README.md'
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: deploy utland-soknad-sendt-topic to dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: kafka-aiven/utland-soknad-sendt.v1/topic.yaml
          VARS: kafka-aiven/utland-soknad-sendt.v1/dev-vars.yaml
          PRINT_PAYLOAD: true
      
      - name: deploy soknad-sendt-topic to dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: kafka-aiven/soknad-sendt.v1/topic.yaml
          VARS: kafka-aiven/soknad-sendt.v1/dev-vars.yaml
          PRINT_PAYLOAD: true

      -   name: deploy soknad-sendt-ny-topic to dev
            uses: nais/deploy/actions/deploy@v1
            env:
              APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
              CLUSTER: dev-gcp
              RESOURCE: kafka-aiven/soknad-sendt-ny.v1/topic.yaml
              VARS: kafka-aiven/soknad-sendt-ny.v1/dev-vars.yaml
              PRINT_PAYLOAD: true


  deploy-prod:
    runs-on: ubuntu-latest
    environment: prod-gcp:aap
    steps:

     - name: Checkout code
       uses: actions/checkout@v3
     - name: deploy utland-soknad-sendt-topic to prod
       uses: nais/deploy/actions/deploy@v1
       env:
         APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
         CLUSTER: prod-gcp
         RESOURCE: kafka-aiven/utland-soknad-sendt.v1/topic.yaml
         VARS: kafka-aiven/utland-soknad-sendt.v1/prod-vars.yaml
         PRINT_PAYLOAD: true

     - name: deploy soknad-sendt-topic to prod
       uses: nais/deploy/actions/deploy@v1
       env:
         APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
         CLUSTER: prod-gcp
         RESOURCE: kafka-aiven/soknad-sendt.v1/topic.yaml
         VARS: kafka-aiven/soknad-sendt.v1/prod-vars.yaml
         PRINT_PAYLOAD: true