name: Deploy kafka topics

on:
  push:
    branches:
      - main
    paths:
      - kafka-aiven/**
      - '!kafka-aiven/README.md'
  workflow_dispatch:

jobs:
  deploy:
        strategy:
            matrix:
              cluster: [ dev-gcp ]
              topic: [ utland-soknad-sendt.v1,soknad-sendt.v1, soknad-ettersendt.v1]
        name: Deploy til ${{matrix.cluster}}
        needs: bygg
        runs-on: ubuntu-latest
        env:
            PRINT_PAYLOAD: true
            APIKEY: ${{secrets.NAIS_DEPLOY_APIKEY}}
            RESOURCE: kafka-aiven/${{matrix.topic}}/topic.yaml
            CLUSTER: ${{matrix.cluster}}
            VARS: kafka-aiven/${{matrix.topic}}/${{matrix.cluster}}.yaml
        steps:
            -   uses: actions/checkout@v3
            -   uses: nais/deploy/actions/deploy@master
