name: Quodana

on:
  push:
    branches:
      - main
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: JetBrains/qodana-action@v3.2.1
      - uses: actions/upload-artifact@v2
        with:
          name: code-inspection
          path: ${{ github.workspace }}/qodana
          retention-days: 5

      - name: Upload to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ github.workspace }}/qodana/report/results/qodana.sarif.json
