name: Sonar

on:
  push:
    branches:
      - main
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  bygg:
    runs-on: ubuntu-latest
    steps:

      - name: Sjekk ut kode
        uses: actions/checkout@v2

      - name: Sett opp Java 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: 'maven'
      - name: Hent tag
        run: |
          echo "TAG=$(date +%Y.%m.%d.%H%M%S)-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
      - name: Kompiler
        run: |
          mvn versions:set -DnewVersion=${TAG}
          mvn --settings .github/.m2/settings.xml sonar:sonar -Dsonar.login=${SONAR_TOKEN}
